Added renderEntityModel trigger
ChatTriggers/ChatTriggers pull request #350
Opened 2022-08-31 10:02 UTC by realfork

An easy way to get entity models.

2022-08-31 10:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChatTriggers/ChatTriggers?pullRequest=350) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChatTriggers/ChatTriggers?pullRequest=350) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChatTriggers/ChatTriggers?pullRequest=350) it.</sub>

2022-08-31 14:55 UTC, realfork commented
**Changes:**

- RenderEntityModel trigger
- EntityCull trigger (Unsure about it, can be deleted)
- MotionUpdatePre + MotionUpdatePost (Not 100% sure what to name these since it isn't technically motion (onUpdateWalkingPlayer))
- Fix to RenderTitle trigger

2022-08-31 17:38 UTC, mattco98 commented
Can you provide use cases for these? For example, if I understand it correctly, the movement trigger can easily be achieved with a tick trigger and an if statement, and I'm not sure what you would use the pre/post versions for, since they are not cancellable. And it seems like instead of adding triggers for model parts, it would be much more useful to add accessors for them to the various entity classes that could be used in the `renderEntity` trigger that already exists.

2022-08-31 18:16 UTC, realfork commented
Most of them are for convenience.

RenderEntityModel - ModelBase is painful to get even with accessors so it's to massively simplify that process.
Movement - Is nicer than writing a tick trigger with the function but it can be removed.
MotionUpdate triggers - For running code before and after movement packets are sent.

2022-08-31 19:02 UTC, mattco98 commented
> RenderEntityModel - ModelBase is painful to get even with accessors so it's to massively simplify that process.

Right, which is why CT can potentially take that burden off of the users with accessors, even if they are "painful". If it is feasible, we should go that route instead. And the bar for feasible for CT code (.kt) is much much lower than it is for user modules. 

> Movement - Is nicer than writing a tick trigger with the function but it can be removed.

I agree with the removal, doesn't seem to have much motivation

> MotionUpdate triggers - For running code before and after movement packets are sent.

That's not a use case, that is what they do, which I can infer from the code. What do you plan on doing with them that cannot be done another way?

2022-09-01 09:42 UTC, realfork commented
Ok, I finally found the way to get main model so I added it to the entity wrapper and removed the trigger. I also removed the movement triggers.

2022-09-01 14:03 UTC, mattco98 requested changes
Looks much better, thanks for refactoring!

2022-09-01 14:03 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Entity.kt
> +    fun getMainModel(): ModelBase = (Client.getMinecraft().renderManager.getEntityRenderObject<net.minecraft.entity.Entity>(entity) as RendererLivingEntity).getMainModel()
Can this cast fail?

2022-09-01 14:03 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Entity.kt
> +    fun getMainModel(): ModelBase = (Client.getMinecraft().renderManager.getEntityRenderObject<net.minecraft.entity.Entity>(entity) as RendererLivingEntity).getMainModel()
We probably want a simple wrapper around `ModelBase` which forwards methods to an underlying implementation so the user doesn't need to use obfuscated methods. See [`Particle`](https://github.com/ChatTriggers/ChatTriggers/blob/master/src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Particle.kt) for an example. Idk what `ModelBase` looks like but as in `Particle`, feel free to change method names or add helper methods if you want.

2022-09-01 14:03 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Entity.kt
> +    fun getMainModel(): ModelBase = (Client.getMinecraft().renderManager.getEntityRenderObject<net.minecraft.entity.Entity>(entity) as RendererLivingEntity).getMainModel()
We should have an `MCEntity` alias in [`TypeAliases.kt`](https://github.com/ChatTriggers/ChatTriggers/blob/master/src/main/kotlin/com/chattriggers/ctjs/utils/kotlin/TypeAliases.kt) so you don't have to write out the full package name

2022-09-01 14:03 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Player.kt
> +    fun isMoving(): Boolean = getPlayer()?.let { it.movementInput.moveForward != 0F || it.movementInput.moveStrafe != 0F } ?: false
Small nitpick to shorten the line a bit:
```suggestion
    fun isMoving(): Boolean = getPlayer()?.movementInput?.let { it.moveForward != 0F || it.moveStrafe != 0F } ?: false
```

2022-09-01 15:46 UTC, realfork commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Entity.kt
> +    fun getMainModel(): ModelBase = (Client.getMinecraft().renderManager.getEntityRenderObject<net.minecraft.entity.Entity>(entity) as RendererLivingEntity).getMainModel()
I don't think so?

2022-10-07 11:30 UTC, realfork commented
Sorry for abandoning this for a while, I removed the model base method since it doesn't actually get the model correctly. Should be ready now.

2022-10-07 11:44 UTC, merged