Add Font class for custom font rendering
ChatTriggers/ChatTriggers pull request #357
Opened 2022-11-02 14:29 UTC by realfork

2022-11-02 17:00 UTC, mattco98 commented
Before I post a review, is there a reason we can't use Elementa's font utilities? Seems like both `FontRenderer` and `BasicFontRenderer` (not sure what the difference is) accepts a `java.awt.Font`.

2022-11-02 17:02 UTC, realfork commented
Maybe, but I seem to remember it's very strange to use and the fonts aren't as smooth as this. Will have a look though and double check in case it has been improved since I last tried it.

2022-11-06 18:45 UTC, realfork commented
I looked into this, the Elementa font renderer uses https://github.com/Chlumsky/msdfgen for generating distance fields to use instead of a .ttf meaning it wouldn't really be suitable for something like CT.

2022-11-07 20:21 UTC, mattco98 requested changes
Did you derive this from somewhere else?

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +    private fun generateColors() {
This method is complete gibberish. Please pick better variable names and add some comments to help the reader understand what is happening. Also, it looks like this (and `colorCodes`) can be static.

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +        private const val COLOR_INVOKER = '\u00a7'
This seems like a strange name. Something like `COLOR_CODE_SYMBOL` would be more appropriate.

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +                if (obfuscated) character = (character.code + RANDOM_OFFSET).toChar()
I'm not sure about this random offset. Presumably we would always want to pick a printable character. Best to check the MC source to see what it does.

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +            val textureId = GlStateManager.generateTexture()
It doesn't look like this has a corresponding `deleteTexture` call, which will leak a lot of memory. We should more or less do the same thing that `Image` does.

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +                buffer.put((pixel shr 16 and 0xFF).toByte())
Please add clarifying parens when chaining bitwise operators (entire file)

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +        val pixels = IntArray(image.width * image.height)
Maybe I'm misunderstanding, but I don't think this intermediate array is necessary, since `BufferedImage` supports individual pixel access

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +                )
```suggestion
                if (strikethrough) {
                    drawLine(
                        Vector2f(0F, charData!!.height / 2f), 
                        Vector2f(charData.width, charData.height / 2f),
                    )
                }

                if (underlined) {
                    drawLine(
                        Vector2f(0F, charData!!.height - 15), 
                        Vector2f(charData.width, charData.height - 15),
                    )
                }
```

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +            val previous = if (i > 0) text[i - 1] else '.'
```suggestion
            val previous = text.getOrElse(i - 1, '.')
```

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +                when ("0123456789abcdefklmnor".indexOf(text.lowercase()[i + 1])) {
Why not just compare against the character directly instead of changing it to an offset?

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +                when ("0123456789abcdefklmnor".indexOf(text.lowercase()[i + 1])) {
Same hereWhy not just compare against the character directly instead of changing it to an offset?

2022-11-07 20:21 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +        generateColors()
This doesn't seem like it needs to be called three times for every construction of `Font`

2022-11-07 21:45 UTC, DJtheRedstoner requested changes
A few general points:
- this doesn't support unicode characters, is this something we want to support?
- would this work in ports to modern versions? or would the restrictions on the awt api prevent this?
- a lot of this reads like a java class (was it converted by intellij? :P), i can give more detailed comments on this if needed

2022-11-07 21:45 UTC, DJtheRedstoner commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +        val inputStream = FileInputStream("${Config.modulesFolder}/$path")
unclosed stream

2022-11-07 21:45 UTC, DJtheRedstoner commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +            createTexture(textureId, characterImage)
Creating a texture for each glyph is not very optimized. Consider creating a glyph atlas.

2022-11-07 21:45 UTC, DJtheRedstoner commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +                    index < 16 -> {
A lot of magic numbers here, can this be done in a nicer way?

2022-11-07 21:45 UTC, DJtheRedstoner commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +        GL11.glTexImage2D(
The majority of this function can be eliminated. By using an internal format of `GL_RGBA8` (`GL_RBGA` would work too, but sized formats are preferred these days), a format of `GL_BGRA` and a type of `GL_UNSIGNED_INT_8_8_8_8_REV`, you can directly pass the `pixels` array to opengl, without any need for transformation.

2022-11-07 21:45 UTC, DJtheRedstoner commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +            regularData = setup(arrayOfNulls(256), Font.PLAIN)
This seems a bit weird, couldn't the array just be constructed inside `setup`? Should also allow the elements to be non-nullable types.

2022-11-07 21:45 UTC, DJtheRedstoner commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Font.kt
> +    internal inner class CharacterData(var width: Float, var height: Float, private val textureId: Int) {
can this be `private`? does it need to be `inner`?

2023-02-02 15:19 UTC, mattco98 commented
Feel free to reopen later if you want to work on this again

2023-02-02 15:19 UTC, closed without merging