Color required module names in gray
ChatTriggers/ChatTriggers pull request #386
Opened 2023-07-20 16:26 UTC by NoahTheNerd

I made this a new pull since the original code was very far gone. This was tested & works. If anyone has issues running it please let me know and I'll look into it.

2023-10-21 21:15 UTC, NoahTheNerd commented
Bump

2024-05-03 18:47 UTC, NoahTheNerd commented
looks good to merge in my opinion

2024-05-04 00:29 UTC, mattco98 requested changes

2024-05-04 00:29 UTC, mattco98 commented on src/main/kotlin/com/chattriggers/ctjs/engine/module/Module.kt
> +                "&7"+metadata.name ?: name
```suggestion
                "&7{metadata.name ?: name}"
```

2024-05-04 00:37 UTC, NoahTheNerd commented
woops, had that in my compiled ver but never commited it! good catch!

2024-05-18 17:30 UTC, NoahTheNerd commented
squashed

2024-05-18 18:26 UTC, merged